FROM node:20-alpine

WORKDIR /app

# copy everything from the current directory  to the docker image. The FIRST dot is the current dir on our machine, the SECOND dot is the path of the cur dir within the container

COPY . .

CMD node hello.js